[package]
name = "choosme"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.7.2", package = "libadwaita", features = ["v1_5"] }
gdk4 = "0.9.6"
gtk4 = "0.9.6"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.0"
